inherit_from: .rubocop.yml

#
# Turn off during guard runs
#

# turn off comment intention check during development 
# because NerdCommenter honors commented code intentions
Style/CommentIndentation:
  Enabled: false
