AllCops:
  RunRailsCops: true

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/AndOr:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  Enabled: false
