language: ruby
rvm:
  - 2.2
  - ruby-head

sudo: false
script: 'ci/travis.rb'
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
addons:
  postgresql: "9.3"
