defaults: &defaults
  app_name: .EE Registry
  zonefile_export_dir: 'export/zonefiles'

  # You can use `rake secret` to generate a secure secret key.
  # Your secret key is used for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!
  secret_key_base: please-change-it-you-can-generate-it-with-rake-secret
  devise_secret: please-change-it-you-can-generate-it-with-rake-secret
  ca_cert_path: ca-cert-path-here
  ca_key_path: ca-key-path-here
  ca_key_password: ca-key-pass-phrase-here

development:
  <<: *defaults

test:
  <<: *defaults

alpha:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
