defaults: &defaults
  app_name: .EE Registry
  zonefile_export_dir: 'export/zonefiles'

development:
  <<: *defaults

test:
  <<: *defaults

alpha:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
