defaults: &defaults
  app_name: .EE Registry
  zonefile_export_dir: 'export/zonefiles'

  # You can use `rake secret` to generate a secure secret key.
  # Your secret key is used for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!
  secret_key_base: please-change-it-you-can-generate-it-with-rake-secret
  devise_secret: please-change-it-you-can-generate-it-with-rake-secret

  # Used by registry admin server:
  crl_path:     '/home/registry/registry/shared/ca/crl/crl.pem'
  ca_cert_path: '/home/registry/registry/shared/ca/certs/ca.crt.pem'
  ca_key_path:  '/home/registry/registry/shared/ca/private/ca.key.pem'
  ca_key_password: 'your-root-key-password'

  # Used by EPP server
  webclient_ip: '54.154.91.240'

development:
  <<: *defaults

test:
  <<: *defaults

alpha:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
