#
# EPP, REPP, Admin and Registrar config
#
# Registrant example is at database-example-registrant.yml file

default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: registry
  password: registry_pwd

#    
# Staging config For EPP, REPP, Admin, Registrar
#

staging:
  <<: *default
  database: registry_staging

whois_staging:
  <<: *default
  database: registry_whois_staging

api_log_staging:
  <<: *default
  database: registry_api_log_staging

#    
# Production config For EPP, REPP, Admin, Registrar
#
production:
  <<: *default
  database: registry_production

whois_production:
  <<: *default
  database: registry_whois_production

api_log_production:
  <<: *default
  database: api_log_production
