default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: registry
  password: registry_pwd


development:
  <<: *default
  database: registry_development

whois_development:
  <<: *default
  database: registry_whois_development

api_log_development:
  <<: *default
  database: registry_api_log_development


test:
  <<: *default
  database: registry_test

whois_test:
  <<: *default
  database: registry_whois_test

api_log_test:
  <<: *default
  database: registry_api_log_test


alpha:
  <<: *default
  database: registry_alpha

whois_alpha:
  <<: *default
  database: registry_whois_alpha

api_log_alpha:
  <<: *default
  database: registry_api_log_alpha


staging:
  <<: *default
  database: registry_staging

whois_staging
  <<: *default
  database: registry_whois_staging

api_log_staging
  <<: *default
  database: registry_api_log_staging


production:
  <<: *default
  database: registry_production

whois_production:
  <<: *default
  database: registry_whois_production

api_log_production:
  <<: *default
  database: api_log_production
