default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: internetee
  password: internetee_pwd

development:
  <<: *default
  database: internetee_development

test:
  <<: *default
  database: internetee_test
