default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: registry
  password: registry_pwd


development:
  <<: *default
  database: registry_development

development:
  <<: *default
  database: registry_whois_development


test:
  <<: *default
  database: registry_test


production:
  <<: *default
  database: registry_production

production:
  <<: *default
  database: registry_whois_production

