development:
  secret_key_base: generate-your-secret-key-by-rake-secret
 
test:
  secret_key_base: generate-your-secret-key-by-rake-secret

alpha:
  secret_key_base: generate-your-secret-key-by-rake-secret

staging:
  secret_key_base: generate-your-secret-key-by-rake-secret

production:
  secret_key_base: generate-your-secret-key-by-rake-secret
